### ISSUE TITLE
How is the data licensed?

### ISSUE THREAD

**Issue by Sogomn** [aocpip/aoe2stats#27]
Am I allowed to used the data for non-commercial projects if I give proper credit? I see the project is licensed with the MIT license but does that apply to the data aswell?

**Comment by szist** [comment]
The data is just information and if anyone has a license for it, it is Microsoft. As far as I'm concerned, feel free to use it  and I would appreciate giving credit to this repository/site. It's not just my time that went into it :)

**Comment by Sogomn** [comment]
Awesome, thank you!
I'm using it for an API regarding AoE 2 info, if that is of matter.
[Repo](https://gitlab.com/Sogomn/nightbot-voobly.)
