### ISSUE TITLE
Investigation from nielkaz

### ISSUE THREAD

**Issue by szist** [aocpip/aoe2stats#9]
CKN's ROF is approximately 3.6 for regular and 3.8 for elites. Thumb ring improves this to about 3.0 and 3.2 respectively.

Wild boar and edible elephant speed is 0.96 as they will follow an archer (0.96) all along the map with the same separation between them.

The Gill Nets tech also improves villager shore fishing by 25%.

**Comment by Jineapple** [comment]
He's correct about the boar and elephant speed, pull request #12 fixes that.

The reload times for Chu Ko Nu are already mentioned, however for normal Chu Ko Nu, the practical value is in the unit details, while for the Elite one the theoretical one is in the details. Probably would be best to choose the approach the Elite one takes. I'll add that to #12 as well.

In the data, Gillnets only increases the work rate of fishing ships, not fishermen. I also did a quick test to be sure, there's no increase for villager shore fishing.

**Comment by szist** [comment]
Integrated and published.
